### ISSUE TITLE
예약 데이터 안넘어오는 문제

### ISSUE THREAD

**Issue by joseph-106** [Web-solute/hoops-frontend#63]
### 문제
예약을 진행하고 `ListModal`과 `QRModal`에서 각각 `data`를 콘솔에 찍어봤을 때,
예약 전과 같이 `data.myReservationToday`는 `[](빈 배열)`, `data.QRValid`는 `null` 값이 넘어옵니다
이 때, 새로고침을 하면 `data.myReservationToday`는 정상적으로 들어오고 `data.QRValid`는 여전히 안들어옵니다

정리하면,

1. 예약 후, 새로고침해야 `ListModal`에서 `data.myReservationToday`가 들어옴
2. 새로고침해도 `QRModal`에는 `data.QRValid` 안들어옴

### 변경사항 (3/13)
[ListModal.js]
``` 
{ data?.myReservationToday.length === 0 
    ? <Subtitle size='16px' top='15px'>예약 내역이 없습니다!</Subtitle> 
    : <div style={{ maxHeight: '400px', overflow: 'auto'}}>
        {data?.myReservationToday?.map((res)=>(
            <ListItem key={res.id}>
                <Subtitle size='14px'>{res.room.roomNumber}번 스터디룸</Subtitle>
                <Subtitle size='17px'> {res.schedule[0].start}-{res.schedule[res.schedule.length-1].finish}</Subtitle>
                <div onClick={() => onClick(res.id)} style={{ display:"inline" ,marginLeft: '7px', verticalAlign: 'middle' }}>
                    <img src={cancel_button} alt='cancel_button'/>
                </div>
            </ListItem>
        ))}
    </div>
}
```

> `data.myReservationToday.length`를 기준으로 데이터 없는 경우 UI 추가, 정상 작동합니다

**Comment by sinbox0701** [comment]
두 데이터 모두 local에서는 데이터 넘어옵니다!

**Comment by joseph-106** [comment]
음.. 그러면 배포 문제일까요
제가 각 모달에 콘솔 이벤트 넣어놨는데

[ListModal.js]
```
<Subtitle size='22px' top='40px' onClick={ ()=>console.log(data) }>나의 예약 내역</Subtitle>
```
[QRModal.js]
```
<QrText onClick={ ()=>console.log(data) }>입장을 위한 QR Code</QrText>
```
리모트에서 콘솔 찍어보면서 확인해볼 수 있을겁니닷

**Comment by joseph-106** [comment]
`data.myReservationToday` 새로고침해야 들어오는 이슈도 로컬에는 없을까요?

**Comment by sinbox0701** [comment]
고거는 있어서 제가 수정하려구욥!

**Comment by sinbox0701** [comment]
새로고침 이슈 변경했는데 확인해주세유!!

**Comment by joseph-106** [comment]
음.. 여전히 새로고침을 한 번 해야 적용되는 것 같습니다

**Comment by joseph-106** [comment]
배포 오류로 리모트 적용 안된 것 같아용! `no-unused-vars` 수정 하고 적용해보겠슴다

+++
새로고침 이슈 해결 되었습니다

**Comment by joseph-106** [comment]
`QRModal` 관련 이슈는 보류하겠습니다
